"""initial

Revision ID: c4fc227bd68f
Revises: 
Create Date: 2025-08-21 21:59:40.516321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fc227bd68f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'TESTING', 'PRODUCTION', name='environment'), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'environment', name='uix_config_name_env')
    )
    op.create_table('feature_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flag_name'), 'feature_flag', ['name'], unique=True)
    op.create_table('feature_config_flag',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('disabled_message', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['feature_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_flag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id', 'feature_id'),
    sa.UniqueConstraint('config_id', 'feature_id', name='uix_config_feature')
    )
    op.create_table('feature_config_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['feature_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'version_number', name='uix_config_version')
    )
    op.create_index(op.f('ix_feature_config_version_config_id'), 'feature_config_version', ['config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_config_version_config_id'), table_name='feature_config_version')
    op.drop_table('feature_config_version')
    op.drop_table('feature_config_flag')
    op.drop_index(op.f('ix_feature_flag_name'), table_name='feature_flag')
    op.drop_table('feature_flag')
    op.drop_table('feature_config')
    # ### end Alembic commands ###
