"""initial

Revision ID: d2c7c8e3621f
Revises: 
Create Date: 2025-08-20 21:14:56.128919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c7c8e3621f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_base_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_free_mode_enable', sa.Boolean(), nullable=False),
    sa.Column('is_collect_metrics_enable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bot_function',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('fee_uses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('base_settings_function',
    sa.Column('base_settings_id', sa.UUID(), nullable=False),
    sa.Column('function_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_settings_id'], ['bot_base_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['function_id'], ['bot_function.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('base_settings_id', 'function_id'),
    sa.UniqueConstraint('base_settings_id', 'function_id', name='uix_settings_func')
    )
    op.create_table('config_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_config_id', sa.UUID(), nullable=False),
    sa.Column('bot_base_settings_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['bot_base_settings_id'], ['bot_base_settings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bot_config_id'], ['bot_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_version_bot_config_id'), 'config_version', ['bot_config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_version_bot_config_id'), table_name='config_version')
    op.drop_table('config_version')
    op.drop_table('base_settings_function')
    op.drop_table('bot_function')
    op.drop_table('bot_config')
    op.drop_table('bot_base_settings')
    # ### end Alembic commands ###
